export const NavLinksList = {
	LINK_EN: [
		{ name: 'Feature', url: '#feature' },
		{ name: 'Playground', url: '/playground' },
		{ name: 'Pricing', url: '#pricing' },
		{ name: 'Testimonial', url: '#testimonial' },
		{ name: 'FAQ', url: '#faq' },
		{ name: 'About', url: '/about' },
		{ name: 'Blog', url: '/blog' },
	],
	LINK_ZH: [
		{ name: '功能', url: '#feature' },
		{ name: 'Playground', url: '/playground' },
		{ name: '定价', url: '#pricing' },
		{ name: '评价', url: '#testimonial' },
		{ name: '常见问题', url: '#faq' },
		{ name: '关于', url: '/about' },
		{ name: '博客', url: '/blog' },
	],
	LINK_ES: [
		{ name: 'Característica', url: '#feature' },
		{ name: 'Playground', url: '/playground' },
		{ name: 'Precios', url: '#pricing' },
		{ name: 'Testimonio', url: '#testimonial' },
		{ name: 'FAQ', url: '#faq' },
		{ name: 'Acerca de', url: '/about' },
		{ name: 'Blog', url: '/blog' },
	],
	LINK_RU: [
		{ name: 'Функция', url: '#feature' },
		{ name: 'Playground', url: '/playground' },
		{ name: 'Цены', url: '#pricing' },
		{ name: 'Отзыв', url: '#testimonial' },
		{ name: 'ЧаВО', url: '#faq' },
		{ name: 'О нас', url: '/about' },
		{ name: 'Блог', url: '/blog' },
	],
	LINK_JA: [
		{ name: '特徴', url: '#feature' },
		{ name: 'Playground', url: '/playground' },
		{ name: '価格', url: '#pricing' },
		{ name: 'お客様の声', url: '#testimonial' },
		{ name: 'よくある質問', url: '#faq' },
		{ name: 'アバウト', url: '/about' },
		{ name: 'ブログ', url: '/blog' },
	],
	LINK_AR: [
		{ name: 'ميزة', url: '#feature' },
		{ name: 'Playground', url: '/playground' },
		{ name: 'التسعير', url: '#pricing' },
		{ name: 'شهادة', url: '#testimonial' },
		{ name: 'الأسئلة الشائعة', url: '#faq' },
		{ name: 'حول', url: '/about' },
		{ name: 'مدونة', url: '/blog' },
	],
	LINK_FR: [
		{ name: 'Fonctionnalités', url: '#feature' },
		{ name: 'Playground', url: '/playground' },
		{ name: 'Tarification', url: '#pricing' },
		{ name: 'Témoignages', url: '#testimonial' },
		{ name: 'FAQ', url: '#faq' },
		{ name: 'À propos', url: '/about' },
		{ name: 'Blog', url: '/blog' },
	],
};
